### ISSUE TITLE
Options do not work

### ISSUE THREAD

**Issue by peterhammer** [gturri/hidden#50] opened 2017-09-06 17:01 UTC
< hidden onHidden=“Click to read more” onVisible=“Click to see less” >Hidden text< / hidden >`

* Had to add extra spaces to the tags because the text was altered when on display mode.

That shows as:
    onHidden=“Click to read more” onVisible=“Click to see less” (*** two arrows ***)

The text "hidden text" is never shown, clicking has no efect. Without options it works OK.

**Comment by gturri** [comment] 2017-09-07 12:15
I just tried it and it seems to work flawlessly. It could be because of the double quotes: instead of “ and ”, you should use the classical character ".  (copy pasting from the documentation page of the plugin on dokuwiki.org can cause this issue, since Dokuwiki interprets the character " and tries to render it in a clever way).

Please let me know if it solves your issue.
If it doesn't, please grant me read access to a page of your wiki where I can observe this issue.

**Comment by gturri** [comment] 2018-02-06 09:16
Closing because "can't reproduce" and "no reply for 5 months".
Feel free to re-open it if you feel it has been closed to quickly

**Closed by gturri** 2018-02-06 09:16 UTC
