### ISSUE TITLE
problem with list

### ISSUE THREAD

**Issue by rastinrastini** [gturri/hidden#29] opened 2014-08-04 12:17 UTC
hi all
when i use in an text like this:
"
&lt;hidden>
this sentence:
1- item1
2- item 2
&lt;/hidden>
next section.
"
then a border is drawed to end of next section.
thankful.

**Comment by gturri** [comment] 2015-08-03 15:14
I'm closing this bug because I can't reproduce, and I have no new info for 1y.
Feel free to open it again if needed.

**Closed by gturri** 2015-08-03 15:14 UTC
